### ISSUE TITLE
Derived Copy CNXML missing metadata

### ISSUE THREAD

**Issue by edwoodward** [openstax/rhaptos.cnxmlutils#119]
Published a derived copy of a Page on beta.cnx.org. The Page published on legacybeta.cnx.org, but the CMXL was missing all of the metadata.  The metadata is in the database because it was displayed in the search results. This may not be a bug, but documenting it here.

Original derived copy in beta.cnx.org
http://beta.cnx.org/contents/3b8b507e-af4d-49e7-8d26-b1a61138a7fc/Ed's_Introduction

Published version on legacybeta.cnx.org
http://legacybeta.cnx.org/content/m53215/latest/

**Comment by pumazi** [comment]
My understanding was that the metadata will be found in the index_auto_generated.cnxml which will be generated by legacy. The transform contains the minimum amount of work necessary to format the content. The idea was to use as much of the existing machinery as possible.

Also, at the moment, we have very little need for the metadata in the cnxml itself.

**Comment by edwoodward** [comment]
I plan on running a test on editing this content to see if the metadata 
gets added as we expect.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
