### ISSUE TITLE
Note Plugin HTML is not correct for Editor plugin

### ISSUE THREAD

**Issue by edwoodward** [openstax/rhaptos.cnxmlutils#127]
The Note HTML is not structured correctly for the Note plugin in the editor.

@amberwebb documented in https://github.com/Connexions/webview/issues/1006

Here is an example of a note that I added into the editor:

https://gist.githubusercontent.com/amberwebb/f8128373b8c9de211371/raw/6251b9a545ef7e1bda2a812f4093191db2630a2e/gistfile1.html

Here is what's being returned in the derived copy:

https://gist.githubusercontent.com/amberwebb/3266d0e55924ddd09146/raw/25940e902dbfefea51f7e7c6ffc33a246b4ef8f3/gistfile1.html

The title div needs to be moved out of the main body of the note and class="title" added to the div. The title dropdown HTML is not in the derived note, although I'm not sure if that is a problem with the plugin or the transform.

**Comment by amberwebb** [comment]
@pumazi Is this an example of the problem you mentioned with the user adding a class of title into the content?

**Comment by pumazi** [comment]
I'm not sure #128 fixes this, but let's hope.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
