### ISSUE TITLE
Bad CNXML in module on production

### ISSUE THREAD

**Issue by edwoodward** [openstax/rhaptos.cnxmlutils#131]
I'm not sure if this came from beta.cnx.org, but I think it might have. When I try to view my author profile (https://legacy.cnx.org/member_profile/ew2), I get this error in Legacy
![screenshot from 2015-05-05 12 50 39](https://cloud.githubusercontent.com/assets/1394695/7479172/730a808a-f325-11e4-892e-a19c5b7e6f27.png)

When I try to view m55490, I get this CNXML error. I get the same error if I try to view the source of the module.
![screenshot from 2015-05-05 12 49 35](https://cloud.githubusercontent.com/assets/1394695/7479195/96d4a1a8-f325-11e4-894f-54b6b47a21d4.png)

**Comment by pumazi** [comment]
I'll need someone with production db access to attach or paste the content of that file here. And please also attach any other html or cnxml files associated with the content. (cc @dtwilliamson @reedstrm )

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
