### ISSUE TITLE
bibtexml is not getting converted

### ISSUE THREAD

**Issue by edwoodward** [openstax/rhaptos.cnxmlutils#134]
There is some new content being created using bibtexml for references. This is perfectly legal in CNXML, but the references are being lost in the HTML.

https://legacy.cnx.org/content/m45096/latest/

http://cnx.org/contents/f5083cb8-fe5e-4287-9717-293e1315d000@4/Introduction-to-Wavelets

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
