### ISSUE TITLE
HTML Transform - table elements are not getting converted

### ISSUE THREAD

**Issue by edwoodward** [openstax/rhaptos.cnxmlutils#136]
In the appendix of Biology, data in a table are not getting converted.

http://cnx.org/contents/b3c1e1d2-839c-42b0-a314-e119a8aafbdd@8.57:105/Appendix

![screenshot from 2015-11-12 15 28 02](https://cloud.githubusercontent.com/assets/1394695/11131783/0736a6fe-8952-11e5-85ea-d637b1d24cb6.png)

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
