### ISSUE TITLE
Figures should not be contained inside para

### ISSUE THREAD

**Issue by mjbuchholz** [openstax/rhaptos.cnxmlutils#142]
There exists an issue in transformation that cte has run into. Some figures (inside of the statistics raw html in particular) are contained inside of para. This causes problems with numbering and generally is invalid. We are wrapping the figures, but this prevents us from being able to access some of the figures contained within problems (b/c they aren't direct children of any class).

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
