### ISSUE TITLE
Page titles should be H2

### ISSUE THREAD

**Issue by helenemccarron** [openstax/rhaptos.cnxmlutils#147]
Currently, the transforms return the page titles as divs.
Current output:
`<div data-type="document-title" id="auto_e911f49c-bb38-49cf-bb03-066373c43a76@8_64861"><span class="number">1.1</span> <span class="divider"> | </span><span class="text">What Is Economics, and Why Is It Important?</span></div>`

Desired output
`<h2  id="auto_e911f49c-bb38-49cf-bb03-066373c43a76@8_64861"><span class="number">1.1</span> <span class="divider"> | </span><span class="text">What Is Economics, and Why Is It Important?</span></h2>`

Please note that the final class/data-type has not been decided yet.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
