### ISSUE TITLE
Question numbering restarting each chapter after EOC nesting changes - no longer matching PDF, etc. 

### ISSUE THREAD

**Issue by yblock** [openstax/rhaptos.cnxmlutils#177]
Book: Astronomy 
Server: Production 
CNX link: https://cnx.org/contents/LnN76Opl@20.2:55W6DXyy@20.2/Review-Questions

![Screen Shot 2019-04-18 at 8.32.23 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/f03c17ee-252e-4000-b05d-e63cfa1093ba)

**Comment by openstaxalina** [comment]
Issue moved to [openstax/cnx-recipes #1019](https://github.com/openstax/cnx-recipes/issues/1019) via [**ZenHub**](https://www.zenhub.com/)
