### ISSUE TITLE
Decide on how to handle labels with markup (media, em, math)

### ISSUE THREAD

**Issue by philschatz** [openstax/rhaptos.cnxmlutils#39]
See #38.

Some things to think about:
- for list labels, can we just move the markup out of the label?
- how would this get implemented in the editor (nested Aloha blocks are very finicky, where does the toolbar go, etc)?
- how much would it take to get webview/PDF/etc to work with it?

**Comment by pumazi** [comment]
I believe this still needs addressed. If I recall correctly, we handle labels on most things, but not on the mentioned tags (media, em and math).

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
