### ISSUE TITLE
Tables - Issues from College Physics

### ISSUE THREAD

**Issue by edwoodward** [openstax/rhaptos.cnxmlutils#60]
This will cover several issues, but I think they are related.

A. “(=1)” aligns far left (due also to column size) instead of center 

OLD: http://cnx.org/content/m42091/1.7/?collection=col11406/1.8
![ex1old](https://cloud.githubusercontent.com/assets/1394695/3586780/9f292ace-0c33-11e4-8cae-fe29d1cf12cf.png)

NEW:http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@8.2:4
![ex1new](https://cloud.githubusercontent.com/assets/1394695/3586784/a55eaee6-0c33-11e4-8043-94d3188bde88.png)

B. occurrences of “1” align left instead of center

OLD: http://cnx.org/content/m42238/1.4/?collection=col11406/1.8
![ex2old](https://cloud.githubusercontent.com/assets/1394695/3586800/d2adeeb6-0c33-11e4-8610-f06899e8f9be.png)

NEW: http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@8.1:115
![ex2new](https://cloud.githubusercontent.com/assets/1394695/3586803/d93833e0-0c33-11e4-910b-4eb546e75f1b.png)

C. first two cells in second row (“n”, “l”) align center instead of left 

OLD: http://cnx.org/content/m42618/1.7/?collection=col11406/1.8
![ex3old](https://cloud.githubusercontent.com/assets/1394695/3586876/5b0e8522-0c34-11e4-81e7-aa3880de2c0b.png)

NEW: http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@8.1:248
![ex3new](https://cloud.githubusercontent.com/assets/1394695/3586880/617a5f94-0c34-11e4-867d-769af8750140.png)

D. “kg” column switches to center alignment

OLD: http://cnx.org/content/m42631/1.3/?collection=col11406/1.8
![ex4old](https://cloud.githubusercontent.com/assets/1394695/3586899/7c94df98-0c34-11e4-925f-184ed1a0ba8a.png)

NEW: http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@8.1:252
![ex4new](https://cloud.githubusercontent.com/assets/1394695/3586902/82902678-0c34-11e4-8717-c51ad443eb4f.png)

E. strange line breaking likely related to footnotes issue

OLD: http://cnx.org/content/m42671/1.5/?collection=col11406/1.8
![ex5old](https://cloud.githubusercontent.com/assets/1394695/3586918/a0e94cee-0c34-11e4-88e6-9dffc5fbd7b7.png)

NEW: http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@8.1:267
![ex5new](https://cloud.githubusercontent.com/assets/1394695/3586920/a742d92a-0c34-11e4-8f14-7ab11621f124.png)

F. formulas in “Abbreviation” column aligning center instead of left

OLD: http://cnx.org/content/m42720/1.5/?collection=col11406/1.8
![ex6old](https://cloud.githubusercontent.com/assets/1394695/3586934/c41f113a-0c34-11e4-95ed-28e3d21c173e.png)

NEW: http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@8.1:282#import-auto-id1211982
![ex6new](https://cloud.githubusercontent.com/assets/1394695/3586937/cdf1bb04-0c34-11e4-9eeb-c112bed5091b.png)

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
