### ISSUE TITLE
Fix invalid MathML

### ISSUE THREAD

**Issue by philschatz** [openstax/rhaptos.cnxmlutils#76]
Turns out we have invalid MathML; probably not worth cleaning up the legacy cnxml but maybe worth adding to the CNXML -> HTML transforms.

A common element is `<msubsup>` with only 2 children (should probably be converted to `<msub>`).

You can find it all over http://legacy.cnx.org/content/m42165/1.5/source?legacy=true (view source and find `msubsup`).

Or, you can see it in Firefox by going to http://archive.cnx.org/contents/ca0b6bf0-e249-45a5-aa43-3088b4f66739@5

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
